# Generated by Django 4.1.6 on 2023-02-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=15)),
                ('video_title', models.CharField(max_length=50)),
                ('channel_id', models.CharField(max_length=25)),
                ('channel_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('published_at', models.CharField(max_length=20)),
                ('thumbnail', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['video_title'], name='video_api_v_video_t_716495_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['description'], name='video_api_v_descrip_fee80e_idx'),
        ),
    ]
