# Generated by Django 4.1.6 on 2023-02-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_api', '0002_alter_video_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
